// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async processAudio(inputPath: string, outputDirectory: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("process_audio", { inputPath, outputDirectory }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runPipelineStage(inputPath: string, outputDirectory: string, stage: string, fastMode: boolean | null, force: boolean | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_pipeline_stage", { inputPath, outputDirectory, stage, fastMode, force }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readOutputPayload(outputDirectory: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_output_payload", { outputDirectory }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getStems(outputDirectory: string) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_stems", { outputDirectory }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHistory() : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAppConfig() : Promise<Result<AppConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setDefaultProjectsDir(path: string) : Promise<Result<AppConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_default_projects_dir", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setupProjectWorkspace(inputPath: string, baseDirectory: string) : Promise<Result<WorkspaceSetupResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("setup_project_workspace", { inputPath, baseDirectory }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPipelineState(outputDirectory: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_pipeline_state", { outputDirectory }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist the integrated LUFS and LRA produced by `stream_audio_metrics` to disk.
 * Written to `{output_directory}/data/dsp_metrics.json` so the Python backend can
 * read it during Stage 5 (AI Director report generation).
 */
async writeDspMetrics(outputDirectory: string, dialogueIntegratedLufs: number, dialogueLoudnessRangeLu: number, musicIntegratedLufs: number, musicLoudnessRangeLu: number, effectsIntegratedLufs: number, effectsLoudnessRangeLu: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_dsp_metrics", { outputDirectory, dialogueIntegratedLufs, dialogueLoudnessRangeLu, musicIntegratedLufs, musicLoudnessRangeLu, effectsIntegratedLufs, effectsLoudnessRangeLu }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Build a static LUFS map offline using fast Rust decoding + EBU R128, then persist to disk.
 * 
 * The returned JSON is shaped as `{ "lufs_graph": { ... } }` so callers can merge it into
 * `payload.metrics`. We additionally persist compatibility flat fields in `dsp_metrics.json`
 * so existing Stage 5 readers can continue reading integrated LUFS values.
 */
async generateStaticMap(outputDirectory: string, stemPaths: Partial<{ [key in string]: string }>) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_static_map", { outputDirectory, stemPaths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stream DSP metrics from the 3-stem WAV set (DX, Music, Effects) to the frontend.
 * 
 * Sends:
 * - `channel`      — `DspFramePayload` at up to 60 FPS during processing (IPC channel).
 * - `dsp-complete` — `DspCompletePayload` once when the file finishes naturally (global event).
 * - `dsp-error`    — `String` if a decode or analysis error occurs (global event).
 * 
 * Calling this command while a previous stream is in progress automatically cancels
 * the previous stream (the shared `cancel_flag` is reset to `false` then re-used).
 */
async streamAudioMetrics(channel: TAURI_CHANNEL<DspFramePayload>, dxPath: string, musicPath: string, effectsPath: string, sourcePath: string, startTime: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stream_audio_metrics", { channel, dxPath, musicPath, effectsPath, sourcePath, startTime }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Signal a running `stream_audio_metrics` call to stop after the current frame.
 */
async stopDspStream() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_dsp_stream") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async seekAudioStream(time: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("seek_audio_stream", { time }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setStemState(stemId: string, isSolo: boolean, isMuted: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_stem_state", { stemId, isSolo, isMuted }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Marks the DSP stage as complete in `stage_state.json`.
 * Called by the frontend after the Rust `stream_audio_metrics` stream ends naturally.
 * This allows `get_pipeline_state` to correctly report 3 completed stages on resume.
 */
async markDspComplete(outputDirectory: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mark_dsp_complete", { outputDirectory }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Invalidate a pipeline stage and all downstream stages.
 * 
 * For non-DSP stages: delegates to Python `--redo-stage <stage>` which deletes artifacts
 * for the target stage and all downstream Python stages.
 * 
 * For the DSP stage: deletes `data/dsp_metrics.json` and clears DSP from `stage_state.json`
 * in Rust only — no Python invocation. The frontend re-runs `generate_static_map` after this.
 * 
 * When redoing `separation` or `transcription`, DSP artifacts are also cleared since DSP runs
 * after both in the UI pipeline order: separation → transcription → DSP → semantics → director.
 */
async redoPipelineStage(outputDirectory: string, stage: string, inputPath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("redo_pipeline_stage", { outputDirectory, stage, inputPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send a single message to the AI Director Python sidecar and return its reply.
 * 
 * The Python process (`src/llm/interactive.py`) communicates over stdin/stdout
 * using newline-delimited JSON:
 * Rust  → Python stdin:  `{"text": "<user message>"}\n`
 * Python → Rust stdout:  `{"type": "ready"}\n`           (once, on startup)
 * `{"tool": "<name>", ...}\n`      (zero or more tool calls)
 * `{"type": "response", "text": "..."}\n`
 * 
 * Each tool call is forwarded to the frontend as an `agent-action` Tauri event.
 * 
 * # Security
 * `workspace_dir` must be an absolute path. The value is passed verbatim as the
 * `WORKSPACE_DIR` environment variable so Python's `_is_path_safe` can correctly
 * sandbox file access to the project workspace.
 */
async sendAgentMessage(text: string, workspaceDir: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_agent_message", { text, workspaceDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDiskInfo(path: string) : Promise<Result<DiskInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_disk_info", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openPath(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppConfig = { default_projects_dir: string; project_root?: string }
export type DiskInfo = { total_bytes: number; available_bytes: number; used_bytes: number }
/**
 * Per-frame payload streamed via the `dsp-frame` Tauri event.
 * All float fields use f32 for compact JSON; the frontend rounds as needed.
 */
export type DspFramePayload = { 
/**
 * Monotonic counter (1-based) of frames processed so far.
 */
frame_index: number; 
/**
 * Elapsed time in seconds at the start of this frame.
 */
timestamp_secs: number; dialogue_momentary_lufs: number; dialogue_short_term_lufs: number; dialogue_true_peak_dbtp: number; dialogue_crest_factor: number; music_momentary_lufs: number; music_short_term_lufs: number; music_true_peak_dbtp: number; music_crest_factor: number; effects_momentary_lufs: number; effects_short_term_lufs: number; effects_true_peak_dbtp: number; effects_crest_factor: number; phase_correlation: number; 
/**
 * Subsampled Lissajous coordinates [[x, y], ...] for vectorscope rendering.
 */
lissajous_points: ([number, number])[]; dialogue_centroid_hz: number; background_centroid_hz: number; speech_pocket_masked: boolean; dialogue_speech_energy: number; background_speech_energy: number; snr_db: number }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type TAURI_CHANNEL<TSend> = null
export type WorkspaceSetupResult = { workspace_dir: string; copied_input_path: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
