#!/usr/bin/env bash
# =============================================================================
# setup-wsl2-dev.sh — WSL2 Development Environment Setup
# =============================================================================
# Installs and configures the GPU (Mesa/OpenGL) and audio (ALSA→PulseAudio)
# stack required to run the Mikup native Vizia binary inside WSL2.
#
# Run once per WSL2 Ubuntu 24.04 installation. Safe to re-run.
#
# Usage:
#   bash scripts/setup-wsl2-dev.sh
# =============================================================================

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

pass() { echo -e "${GREEN}[PASS]${NC} $1"; }
fail() { echo -e "${RED}[FAIL]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
info() { echo -e "       $1"; }

# ── Guard: must be WSL2 ──────────────────────────────────────────────────────
if ! grep -qi "microsoft" /proc/version 2>/dev/null; then
    fail "Not running inside WSL2. This script is WSL2-only."
    exit 1
fi

echo ""
echo "=== Mikup WSL2 Dev Environment Setup ==="
echo "    Ubuntu $(. /etc/os-release && echo "$VERSION")"
echo ""

# ── 1. Package installs ───────────────────────────────────────────────────────
echo "--- Installing packages ---"
sudo apt-get update -qq

sudo apt-get install -y \
    mesa-utils \
    mesa-utils-bin \
    libgl1-mesa-dri \
    libglx-mesa0 \
    libegl-mesa0 \
    mesa-vulkan-drivers \
    pulseaudio \
    pulseaudio-utils \
    alsa-utils \
    libasound2-plugins

echo ""

# ── 2. ALSA → PulseAudio bridge ──────────────────────────────────────────────
echo "--- Configuring ALSA → PulseAudio bridge ---"

ASOUNDRC="$HOME/.asoundrc"

cat > "$ASOUNDRC" << 'EOF'
# Route all ALSA audio through WSLg PulseAudio.
# Generated by scripts/setup-wsl2-dev.sh — do not edit manually.
pcm.default pulse
ctl.default pulse
pcm.!default pulse
ctl.!default pulse
EOF

info "Written: $ASOUNDRC"
echo ""

# ── 3. Verification ───────────────────────────────────────────────────────────
echo "--- Running verification tests ---"
FAILURES=0

# Test 1: /dev/dxg (WSLg kernel GPU driver)
if [ -e /dev/dxg ]; then
    pass "WSLg GPU driver present (/dev/dxg)"
else
    fail "/dev/dxg missing — WSLg GPU driver not loaded. Ensure Windows GPU drivers are up to date."
    FAILURES=$((FAILURES + 1))
fi

# Test 2: /dev/dri (Mesa DRI devices)
if ls /dev/dri/ &>/dev/null; then
    pass "DRI devices present ($(ls /dev/dri/ | tr '\n' ' '))"
else
    fail "/dev/dri/ missing — Mesa DRI not initialised. Try restarting WSL2: 'wsl --shutdown' from PowerShell."
    FAILURES=$((FAILURES + 1))
fi

# Test 3: OpenGL renderer
if command -v glxinfo &>/dev/null; then
    RENDERER=$(DISPLAY=:0 glxinfo 2>/dev/null | grep "OpenGL renderer" || echo "")
    if [ -n "$RENDERER" ]; then
        pass "OpenGL context acquired"
        info "$RENDERER"
    else
        warn "glxinfo ran but could not acquire OpenGL context. Software fallback may be active."
    fi
else
    fail "glxinfo not found — mesa-utils may not have installed correctly."
    FAILURES=$((FAILURES + 1))
fi

# Test 4: PulseAudio server reachable
if [ -n "${PULSE_SERVER:-}" ] || [ -S /mnt/wslg/PulseServer ]; then
    PULSE_SINK=$(PULSE_SERVER=unix:/mnt/wslg/PulseServer pactl list sinks short 2>/dev/null || echo "")
    if [ -n "$PULSE_SINK" ]; then
        pass "PulseAudio server reachable, sinks detected"
        info "$PULSE_SINK"
    else
        warn "PulseAudio server found but no sinks enumerated. Audio may still work via WSLg virtual device."
    fi
else
    fail "PulseAudio server socket not found at /mnt/wslg/PulseServer. Ensure WSLg is enabled."
    FAILURES=$((FAILURES + 1))
fi

# Test 5: ALSA default device resolves through PulseAudio
if command -v aplay &>/dev/null; then
    ALSA_DEFAULT=$(PULSE_SERVER=unix:/mnt/wslg/PulseServer aplay -L 2>/dev/null | grep "^default" || echo "")
    if [ -n "$ALSA_DEFAULT" ]; then
        pass "ALSA default device resolves via PulseAudio bridge"
    else
        warn "ALSA default device not found. The .asoundrc bridge may need a session restart to take effect."
    fi
else
    fail "aplay not found — alsa-utils may not have installed correctly."
    FAILURES=$((FAILURES + 1))
fi

# Test 6: cpal will find an output device (simulate what Rust does)
if command -v pactl &>/dev/null; then
    SINK_COUNT=$(PULSE_SERVER=unix:/mnt/wslg/PulseServer pactl list sinks 2>/dev/null | grep -c "^Sink #" || echo "0")
    if [ "$SINK_COUNT" -gt 0 ]; then
        pass "cpal-visible audio output sinks: $SINK_COUNT"
    else
        fail "No PulseAudio sinks — cpal will fall into silent mode."
        FAILURES=$((FAILURES + 1))
    fi
else
    warn "pactl not available — skipping cpal sink check."
fi

echo ""

# ── 4. Summary ────────────────────────────────────────────────────────────────
if [ "$FAILURES" -eq 0 ]; then
    echo -e "${GREEN}=== All checks passed. WSL2 dev environment ready. ===${NC}"
    echo ""
    echo "Next step: rebuild and run the native binary"
    echo "  cd native && cargo run"
else
    echo -e "${RED}=== $FAILURES check(s) failed. ===${NC}"
    echo ""
    echo "If /dev/dri/ is missing after install, restart WSL2 from PowerShell:"
    echo "  wsl --shutdown"
    echo "Then reopen your terminal and re-run this script."
    exit 1
fi
